webtalk_init -webtalk_dir C:/Users/Marcin/VERILOG/test_rozmiar/hdmi_zybo_vga_axis_ps_vdma/hdmi_vga_zybo.hw/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Dec 17 02:06:37 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vivado v2015.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1412921" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211124602_0_0_061" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e6494a2d-eff5-4d31-ac78-0ac0b8986722" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "3fbbf88f-1fc0-45c0-9a9e-7a8b2c312e2c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2494 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client labtool
webtalk_add_data -client labtool -key pgmcnt -value "00:00:00" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "" -context "labtool\\usage"
webtalk_transmit -clientid 799310128 -regid "211124602_0_0_061" -xml C:/Users/Marcin/VERILOG/test_rozmiar/hdmi_zybo_vga_axis_ps_vdma/hdmi_vga_zybo.hw/webtalk/usage_statistics_ext_labtool.xml -html C:/Users/Marcin/VERILOG/test_rozmiar/hdmi_zybo_vga_axis_ps_vdma/hdmi_vga_zybo.hw/webtalk/usage_statistics_ext_labtool.html -wdm C:/Users/Marcin/VERILOG/test_rozmiar/hdmi_zybo_vga_axis_ps_vdma/hdmi_vga_zybo.hw/webtalk/usage_statistics_ext_labtool.wdm -intro "<H3>LABTOOL Usage Report</H3><BR>"
webtalk_terminate
