# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config  -ruleid {2147483647}  -id {IP_Flow 19-1663}  -string {{CRITICAL WARNING: [IP_Flow 19-1663] Duplicate IP found for 'DigilentInc:user:Digi_LED:1.0'. The one found in IP location '/home/marshall/workspace/ip_repo/Digi_LED_1.0' will take precedence over the same IP in location /home/marshall/workspace/ip_repo/edit_Digi_LED_v1_0.srcs/sources_1/imports/Digi_LED_1.0}}  -suppress 
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Marcin/VERILOG/test_rozmiar/hdmi_zybo_vga_axis_ps_vdma/hdmi_vga_zybo.cache/wt [current_project]
set_property parent.project_path C:/Users/Marcin/VERILOG/test_rozmiar/hdmi_zybo_vga_axis_ps_vdma/hdmi_vga_zybo.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  c:/Users/Marcin/VERILOG/test_rozmiar/hdmi_zybo_vga_axis_ps_vdma/hdmi_library
  c:/Users/Marcin/VERILOG/magisterium/magisterium.srcs/sources_1/tcl/dvi2rgb_v1_6
} [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files C:/Users/Marcin/VERILOG/test_rozmiar/hdmi_zybo_vga_axis_ps_vdma/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga_vision/hdmi_vga_vision.bd
set_property used_in_implementation false [get_files -all c:/Users/Marcin/VERILOG/test_rozmiar/hdmi_zybo_vga_axis_ps_vdma/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga_vision/ip/hdmi_vga_vision_clk_wiz_0_0/hdmi_vga_vision_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Marcin/VERILOG/test_rozmiar/hdmi_zybo_vga_axis_ps_vdma/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga_vision/ip/hdmi_vga_vision_clk_wiz_0_0/hdmi_vga_vision_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Marcin/VERILOG/test_rozmiar/hdmi_zybo_vga_axis_ps_vdma/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga_vision/ip/hdmi_vga_vision_clk_wiz_0_0/hdmi_vga_vision_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Marcin/VERILOG/test_rozmiar/hdmi_zybo_vga_axis_ps_vdma/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga_vision/ip/hdmi_vga_vision_v_vid_in_axi4s_0_0/hdmi_vga_vision_v_vid_in_axi4s_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Marcin/VERILOG/test_rozmiar/hdmi_zybo_vga_axis_ps_vdma/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga_vision/ip/hdmi_vga_vision_v_vid_in_axi4s_0_0/hdmi_vga_vision_v_vid_in_axi4s_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Marcin/VERILOG/test_rozmiar/hdmi_zybo_vga_axis_ps_vdma/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga_vision/ip/hdmi_vga_vision_v_tc_0_0/hdmi_vga_vision_v_tc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Marcin/VERILOG/test_rozmiar/hdmi_zybo_vga_axis_ps_vdma/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga_vision/ip/hdmi_vga_vision_v_tc_0_0/hdmi_vga_vision_v_tc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Marcin/VERILOG/test_rozmiar/hdmi_zybo_vga_axis_ps_vdma/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga_vision/ip/hdmi_vga_vision_v_axi4s_vid_out_0_0/hdmi_vga_vision_v_axi4s_vid_out_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Marcin/VERILOG/test_rozmiar/hdmi_zybo_vga_axis_ps_vdma/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga_vision/ip/hdmi_vga_vision_v_axi4s_vid_out_0_0/hdmi_vga_vision_v_axi4s_vid_out_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Marcin/VERILOG/test_rozmiar/hdmi_zybo_vga_axis_ps_vdma/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga_vision/ip/hdmi_vga_vision_processing_system7_0_0/hdmi_vga_vision_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Marcin/VERILOG/test_rozmiar/hdmi_zybo_vga_axis_ps_vdma/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga_vision/ip/hdmi_vga_vision_rst_processing_system7_0_100M_0/hdmi_vga_vision_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Marcin/VERILOG/test_rozmiar/hdmi_zybo_vga_axis_ps_vdma/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga_vision/ip/hdmi_vga_vision_rst_processing_system7_0_100M_0/hdmi_vga_vision_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Marcin/VERILOG/test_rozmiar/hdmi_zybo_vga_axis_ps_vdma/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga_vision/ip/hdmi_vga_vision_rst_processing_system7_0_100M_0/hdmi_vga_vision_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Marcin/VERILOG/test_rozmiar/hdmi_zybo_vga_axis_ps_vdma/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga_vision/ip/hdmi_vga_vision_axi_vdma_0_0/hdmi_vga_vision_axi_vdma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Marcin/VERILOG/test_rozmiar/hdmi_zybo_vga_axis_ps_vdma/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga_vision/ip/hdmi_vga_vision_axi_vdma_0_0/hdmi_vga_vision_axi_vdma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Marcin/VERILOG/test_rozmiar/hdmi_zybo_vga_axis_ps_vdma/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga_vision/ip/hdmi_vga_vision_axi_vdma_0_0/hdmi_vga_vision_axi_vdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Marcin/VERILOG/test_rozmiar/hdmi_zybo_vga_axis_ps_vdma/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga_vision/ip/hdmi_vga_vision_xbar_0/hdmi_vga_vision_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Marcin/VERILOG/test_rozmiar/hdmi_zybo_vga_axis_ps_vdma/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga_vision/ip/hdmi_vga_vision_auto_pc_0/hdmi_vga_vision_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Marcin/VERILOG/test_rozmiar/hdmi_zybo_vga_axis_ps_vdma/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga_vision/ip/hdmi_vga_vision_auto_pc_1/hdmi_vga_vision_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Marcin/VERILOG/test_rozmiar/hdmi_zybo_vga_axis_ps_vdma/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga_vision/ip/hdmi_vga_vision_auto_us_0/hdmi_vga_vision_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Marcin/VERILOG/test_rozmiar/hdmi_zybo_vga_axis_ps_vdma/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga_vision/ip/hdmi_vga_vision_auto_us_0/hdmi_vga_vision_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all C:/Users/Marcin/VERILOG/test_rozmiar/hdmi_zybo_vga_axis_ps_vdma/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga_vision/hdmi_vga_vision_ooc.xdc]
set_property is_locked true [get_files C:/Users/Marcin/VERILOG/test_rozmiar/hdmi_zybo_vga_axis_ps_vdma/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga_vision/hdmi_vga_vision.bd]

read_verilog -library xil_defaultlib C:/Users/Marcin/VERILOG/test_rozmiar/hdmi_zybo_vga_axis_ps_vdma/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga_vision/hdl/hdmi_vga_vision_wrapper.v
read_xdc C:/Users/Marcin/VERILOG/test_rozmiar/hdmi_zybo_vga_axis_ps_vdma/hdmi_vga_zybo.srcs/constrs_1/imports/Downloads/ZYBO_Master.xdc
set_property used_in_implementation false [get_files C:/Users/Marcin/VERILOG/test_rozmiar/hdmi_zybo_vga_axis_ps_vdma/hdmi_vga_zybo.srcs/constrs_1/imports/Downloads/ZYBO_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top hdmi_vga_vision_wrapper -part xc7z010clg400-1
write_checkpoint -noxdef hdmi_vga_vision_wrapper.dcp
catch { report_utilization -file hdmi_vga_vision_wrapper_utilization_synth.rpt -pb hdmi_vga_vision_wrapper_utilization_synth.pb }
