# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/ZYBO_Master.xdc

# Block Designs: bd/hdmi_vga_vision/hdmi_vga_vision.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_vga_vision || ORIG_REF_NAME==hdmi_vga_vision}]

# IP: bd/hdmi_vga_vision/ip/hdmi_vga_vision_dvi2rgb_0_0/hdmi_vga_vision_dvi2rgb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_vga_vision_dvi2rgb_0_0 || ORIG_REF_NAME==hdmi_vga_vision_dvi2rgb_0_0}]

# IP: bd/hdmi_vga_vision/ip/hdmi_vga_vision_clk_wiz_0_0/hdmi_vga_vision_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_vga_vision_clk_wiz_0_0 || ORIG_REF_NAME==hdmi_vga_vision_clk_wiz_0_0}]

# IP: bd/hdmi_vga_vision/ip/hdmi_vga_vision_rgb2vga_0_0/hdmi_vga_vision_rgb2vga_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_vga_vision_rgb2vga_0_0 || ORIG_REF_NAME==hdmi_vga_vision_rgb2vga_0_0}]

# IP: bd/hdmi_vga_vision/ip/hdmi_vga_vision_xlconstant_0_0/hdmi_vga_vision_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_vga_vision_xlconstant_0_0 || ORIG_REF_NAME==hdmi_vga_vision_xlconstant_0_0}]

# IP: bd/hdmi_vga_vision/ip/hdmi_vga_vision_xlconstant_0_1/hdmi_vga_vision_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_vga_vision_xlconstant_0_1 || ORIG_REF_NAME==hdmi_vga_vision_xlconstant_0_1}]

# IP: bd/hdmi_vga_vision/ip/hdmi_vga_vision_v_vid_in_axi4s_0_0/hdmi_vga_vision_v_vid_in_axi4s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_vga_vision_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==hdmi_vga_vision_v_vid_in_axi4s_0_0}]

# IP: bd/hdmi_vga_vision/ip/hdmi_vga_vision_xlconstant_0_2/hdmi_vga_vision_xlconstant_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_vga_vision_xlconstant_0_2 || ORIG_REF_NAME==hdmi_vga_vision_xlconstant_0_2}]

# IP: bd/hdmi_vga_vision/ip/hdmi_vga_vision_v_tc_0_0/hdmi_vga_vision_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_vga_vision_v_tc_0_0 || ORIG_REF_NAME==hdmi_vga_vision_v_tc_0_0}]

# IP: bd/hdmi_vga_vision/ip/hdmi_vga_vision_v_axi4s_vid_out_0_0/hdmi_vga_vision_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_vga_vision_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==hdmi_vga_vision_v_axi4s_vid_out_0_0}]

# XDC: bd/hdmi_vga_vision/ip/hdmi_vga_vision_dvi2rgb_0_0/src/dvi2rgb.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_vga_vision_dvi2rgb_0_0 || ORIG_REF_NAME==hdmi_vga_vision_dvi2rgb_0_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_vga_vision/ip/hdmi_vga_vision_dvi2rgb_0_0/src/dvi2rgb_ooc.xdc

# XDC: bd/hdmi_vga_vision/ip/hdmi_vga_vision_clk_wiz_0_0/hdmi_vga_vision_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_vga_vision_clk_wiz_0_0 || ORIG_REF_NAME==hdmi_vga_vision_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/hdmi_vga_vision/ip/hdmi_vga_vision_clk_wiz_0_0/hdmi_vga_vision_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_vga_vision_clk_wiz_0_0 || ORIG_REF_NAME==hdmi_vga_vision_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/hdmi_vga_vision/ip/hdmi_vga_vision_clk_wiz_0_0/hdmi_vga_vision_clk_wiz_0_0_ooc.xdc

# XDC: bd/hdmi_vga_vision/ip/hdmi_vga_vision_v_vid_in_axi4s_0_0/hdmi_vga_vision_v_vid_in_axi4s_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_vga_vision_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==hdmi_vga_vision_v_vid_in_axi4s_0_0}] {/inst }]/inst ]]

# XDC: bd/hdmi_vga_vision/ip/hdmi_vga_vision_v_vid_in_axi4s_0_0/hdmi_vga_vision_v_vid_in_axi4s_0_0_ooc.xdc

# XDC: bd/hdmi_vga_vision/ip/hdmi_vga_vision_v_tc_0_0/hdmi_vga_vision_v_tc_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_vga_vision_v_tc_0_0 || ORIG_REF_NAME==hdmi_vga_vision_v_tc_0_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_vga_vision/ip/hdmi_vga_vision_v_tc_0_0/hdmi_vga_vision_v_tc_0_0_ooc.xdc

# XDC: bd/hdmi_vga_vision/ip/hdmi_vga_vision_v_axi4s_vid_out_0_0/hdmi_vga_vision_v_axi4s_vid_out_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_vga_vision_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==hdmi_vga_vision_v_axi4s_vid_out_0_0}] {/inst }]/inst ]]

# XDC: bd/hdmi_vga_vision/ip/hdmi_vga_vision_v_axi4s_vid_out_0_0/hdmi_vga_vision_v_axi4s_vid_out_0_0_ooc.xdc

# XDC: bd/hdmi_vga_vision/hdmi_vga_vision_ooc.xdc
