# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/project_2.hw/ZYBO_Master.xdc

# Block Designs: bd/zordon/zordon.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zordon || ORIG_REF_NAME==zordon}]

# IP: bd/zordon/ip/zordon_rgb2vga_0_0/zordon_rgb2vga_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zordon_rgb2vga_0_0 || ORIG_REF_NAME==zordon_rgb2vga_0_0}]

# IP: bd/zordon/ip/zordon_xlconstant_0_0/zordon_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zordon_xlconstant_0_0 || ORIG_REF_NAME==zordon_xlconstant_0_0}]

# IP: bd/zordon/ip/zordon_xlconstant_0_1/zordon_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zordon_xlconstant_0_1 || ORIG_REF_NAME==zordon_xlconstant_0_1}]

# IP: bd/zordon/ip/zordon_dvi2rgb_0_1/zordon_dvi2rgb_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zordon_dvi2rgb_0_1 || ORIG_REF_NAME==zordon_dvi2rgb_0_1}]

# IP: bd/zordon/ip/zordon_clk_wiz_0_0/zordon_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zordon_clk_wiz_0_0 || ORIG_REF_NAME==zordon_clk_wiz_0_0}]

# IP: bd/zordon/ip/zordon_RGB_unpack_0_0/zordon_RGB_unpack_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zordon_RGB_unpack_0_0 || ORIG_REF_NAME==zordon_RGB_unpack_0_0}]

# IP: bd/zordon/ip/zordon_RGB_pack_0_0/zordon_RGB_pack_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zordon_RGB_pack_0_0 || ORIG_REF_NAME==zordon_RGB_pack_0_0}]

# IP: bd/zordon/ip/zordon_binary_0_0/zordon_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zordon_binary_0_0 || ORIG_REF_NAME==zordon_binary_0_0}]

# IP: bd/zordon/ip/zordon_srodek_0_0/zordon_srodek_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zordon_srodek_0_0 || ORIG_REF_NAME==zordon_srodek_0_0}]

# IP: bd/zordon/ip/zordon_srodek_0_0/src/mult_30_20_lm/mult_30_20_lm.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_30_20_lm || ORIG_REF_NAME==mult_30_20_lm}]

# IP: bd/zordon/ip/zordon_srodek_0_0/src/akumulator_inst/akumulator_inst.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==akumulator_inst || ORIG_REF_NAME==akumulator_inst}]

# IP: bd/zordon/ip/zordon_srodek_0_0/src/akumulator_inst/src/sum/sum.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sum || ORIG_REF_NAME==sum}]

# IP: bd/zordon/ip/zordon_proste_0_0/zordon_proste_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zordon_proste_0_0 || ORIG_REF_NAME==zordon_proste_0_0}]

# IP: bd/zordon/ip/zordon_processing_system7_0_0/zordon_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zordon_processing_system7_0_0 || ORIG_REF_NAME==zordon_processing_system7_0_0}]

# IP: bd/zordon/ip/zordon_axi_gpio_0_0/zordon_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zordon_axi_gpio_0_0 || ORIG_REF_NAME==zordon_axi_gpio_0_0}]

# IP: bd/zordon/ip/zordon_ps7_0_axi_periph_0/zordon_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zordon_ps7_0_axi_periph_0 || ORIG_REF_NAME==zordon_ps7_0_axi_periph_0}]

# IP: bd/zordon/ip/zordon_rst_ps7_0_50M_0/zordon_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zordon_rst_ps7_0_50M_0 || ORIG_REF_NAME==zordon_rst_ps7_0_50M_0}]

# IP: bd/zordon/ip/zordon_AXI_Slave_0_2/zordon_AXI_Slave_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zordon_AXI_Slave_0_2 || ORIG_REF_NAME==zordon_AXI_Slave_0_2}]

# IP: bd/zordon/ip/zordon_xbar_0/zordon_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zordon_xbar_0 || ORIG_REF_NAME==zordon_xbar_0}]

# IP: bd/zordon/ip/zordon_grey_scale_0_0_1/zordon_grey_scale_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zordon_grey_scale_0_0 || ORIG_REF_NAME==zordon_grey_scale_0_0}]

# IP: bd/zordon/ip/zordon_grey_scale_0_0_1/src/sum_grey/sum_grey.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sum_grey || ORIG_REF_NAME==sum_grey}]

# IP: bd/zordon/ip/zordon_grey_scale_0_0_1/src/mul/mul.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mul || ORIG_REF_NAME==mul}]

# IP: bd/zordon/ip/zordon_gradient_hessian_0_0/zordon_gradient_hessian_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zordon_gradient_hessian_0_0 || ORIG_REF_NAME==zordon_gradient_hessian_0_0}]

# IP: bd/zordon/ip/zordon_gradient_hessian_0_0/src/delayLineBRAM/delayLineBRAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==delayLineBRAM || ORIG_REF_NAME==delayLineBRAM}]

# IP: bd/zordon/ip/zordon_mux_6_1_0_0/zordon_mux_6_1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zordon_mux_6_1_0_0 || ORIG_REF_NAME==zordon_mux_6_1_0_0}]

# IP: bd/zordon/ip/zordon_auto_pc_0/zordon_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zordon_auto_pc_0 || ORIG_REF_NAME==zordon_auto_pc_0}]

# XDC: bd/zordon/ip/zordon_dvi2rgb_0_1/src/dvi2rgb.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zordon_dvi2rgb_0_1 || ORIG_REF_NAME==zordon_dvi2rgb_0_1}] {/U0 }]/U0 ]]

# XDC: bd/zordon/ip/zordon_dvi2rgb_0_1/src/dvi2rgb_ooc.xdc

# XDC: bd/zordon/ip/zordon_clk_wiz_0_0/zordon_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zordon_clk_wiz_0_0 || ORIG_REF_NAME==zordon_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/zordon/ip/zordon_clk_wiz_0_0/zordon_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zordon_clk_wiz_0_0 || ORIG_REF_NAME==zordon_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/zordon/ip/zordon_clk_wiz_0_0/zordon_clk_wiz_0_0_ooc.xdc

# XDC: bd/zordon/ip/zordon_processing_system7_0_0/zordon_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zordon_processing_system7_0_0 || ORIG_REF_NAME==zordon_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/zordon/ip/zordon_axi_gpio_0_0/zordon_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zordon_axi_gpio_0_0 || ORIG_REF_NAME==zordon_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/zordon/ip/zordon_axi_gpio_0_0/zordon_axi_gpio_0_0_ooc.xdc

# XDC: bd/zordon/ip/zordon_axi_gpio_0_0/zordon_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zordon_axi_gpio_0_0 || ORIG_REF_NAME==zordon_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/zordon/ip/zordon_rst_ps7_0_50M_0/zordon_rst_ps7_0_50M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zordon_rst_ps7_0_50M_0 || ORIG_REF_NAME==zordon_rst_ps7_0_50M_0}] {/U0 }]/U0 ]]

# XDC: bd/zordon/ip/zordon_rst_ps7_0_50M_0/zordon_rst_ps7_0_50M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zordon_rst_ps7_0_50M_0 || ORIG_REF_NAME==zordon_rst_ps7_0_50M_0}] {/U0 }]/U0 ]]

# XDC: bd/zordon/ip/zordon_rst_ps7_0_50M_0/zordon_rst_ps7_0_50M_0_ooc.xdc

# XDC: bd/zordon/ip/zordon_xbar_0/zordon_xbar_0_ooc.xdc

# XDC: bd/zordon/ip/zordon_gradient_hessian_0_0/src/delayLineBRAM/delayLineBRAM_ooc.xdc

# XDC: bd/zordon/ip/zordon_auto_pc_0/zordon_auto_pc_0_ooc.xdc

# XDC: bd/zordon/zordon_ooc.xdc
