# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Marcin/VERILOG/magisterium/magisterium.cache/wt [current_project]
set_property parent.project_path C:/Users/Marcin/VERILOG/magisterium/magisterium.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  c:/Users/Marcin/VERILOG/magisterium/magisterium.srcs/sources_1/if
  c:/Users/Marcin/VERILOG/magisterium/magisterium.srcs/sources_1/tcl
} [current_project]
set_property ip_cache_permissions disable [current_project]
read_verilog -library xil_defaultlib C:/Users/Marcin/VERILOG/magisterium/magisterium.srcs/sources_1/bd/zordon/hdl/zordon_wrapper.v
add_files C:/Users/Marcin/VERILOG/magisterium/magisterium.srcs/sources_1/bd/zordon/zordon.bd
set_property used_in_implementation false [get_files -all c:/Users/Marcin/VERILOG/magisterium/magisterium.srcs/sources_1/bd/zordon/ip/zordon_dvi2rgb_0_1/src/dvi2rgb.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Marcin/VERILOG/magisterium/magisterium.srcs/sources_1/bd/zordon/ip/zordon_dvi2rgb_0_1/src/dvi2rgb_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Marcin/VERILOG/magisterium/magisterium.srcs/sources_1/bd/zordon/ip/zordon_clk_wiz_0_0/zordon_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Marcin/VERILOG/magisterium/magisterium.srcs/sources_1/bd/zordon/ip/zordon_clk_wiz_0_0/zordon_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Marcin/VERILOG/magisterium/magisterium.srcs/sources_1/bd/zordon/ip/zordon_clk_wiz_0_0/zordon_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Marcin/VERILOG/magisterium/magisterium.srcs/sources_1/bd/zordon/ip/zordon_processing_system7_0_0/zordon_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Marcin/VERILOG/magisterium/magisterium.srcs/sources_1/bd/zordon/ip/zordon_axi_gpio_0_0/zordon_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Marcin/VERILOG/magisterium/magisterium.srcs/sources_1/bd/zordon/ip/zordon_axi_gpio_0_0/zordon_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Marcin/VERILOG/magisterium/magisterium.srcs/sources_1/bd/zordon/ip/zordon_axi_gpio_0_0/zordon_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Marcin/VERILOG/magisterium/magisterium.srcs/sources_1/bd/zordon/ip/zordon_rst_ps7_0_50M_0/zordon_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Marcin/VERILOG/magisterium/magisterium.srcs/sources_1/bd/zordon/ip/zordon_rst_ps7_0_50M_0/zordon_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Marcin/VERILOG/magisterium/magisterium.srcs/sources_1/bd/zordon/ip/zordon_rst_ps7_0_50M_0/zordon_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Marcin/VERILOG/magisterium/magisterium.srcs/sources_1/bd/zordon/ip/zordon_xbar_0/zordon_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Marcin/VERILOG/magisterium/magisterium.srcs/sources_1/bd/zordon/ip/zordon_auto_pc_0/zordon_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/Marcin/VERILOG/magisterium/magisterium.srcs/sources_1/bd/zordon/zordon_ooc.xdc]
set_property is_locked true [get_files C:/Users/Marcin/VERILOG/magisterium/magisterium.srcs/sources_1/bd/zordon/zordon.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Marcin/VERILOG/magisterium/magisterium.srcs/constrs_1/imports/project_2.hw/ZYBO_Master.xdc
set_property used_in_implementation false [get_files C:/Users/Marcin/VERILOG/magisterium/magisterium.srcs/constrs_1/imports/project_2.hw/ZYBO_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top zordon_wrapper -part xc7z010clg400-1


write_checkpoint -force -noxdef zordon_wrapper.dcp

catch { report_utilization -file zordon_wrapper_utilization_synth.rpt -pb zordon_wrapper_utilization_synth.pb }
